config/routes.rb
CityCakes::Application.routes.draw do

  resources :microposts, only: [ :create, :destroy ]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :home
  resources :products
  resources :shopping_cart_items

  match '/signup',  to: 'users#new'
  match '/help', to:    'home#help'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :orders do
    collection do
      post 'add_item', 'submit'
      get 'confirm', 'index'
      delete 'remove_item'
    end
  end

  root :to => 'home#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
has many:products
end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
   attr_accessible :content
   belongs_to :user
   validates :user_id, presence: true
   validates  :content, :length => { :maximum => 140 }
   default_scope order: 'microposts.created_at DESC'

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many:order_items
  has_one:shipping_address

  OPEN = 0
  PLACED = 1
  PROCESSED = 2
  CANCELED = 3

  def recalculate
    total = 0
    self.order_items.each do |item|
      total += item.quantity * item.price
    end
    self.subtotal = total
    self.save!
  end
end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to:company
  has_many :order_items
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>", :large => "400x400" }

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

 REGULAR_CAKES = 1
 WEDDING_CAKES = 2
 SPECIAL_CAKES = 3
 CHILDREN_CAKES = 4
 NUMBERERD_CAKES = 5

end

app/models/shipping_address.rb
class ShippingAddress < ActiveRecord::Base
end

app/models/shopping_cart_item.rb
class ShoppingCartItem < ActiveRecord::Base
belongs_to:user
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation
  has_secure_password

  has_many :microposts,  dependent: :destroy
  has_many :shopping_cart_items
  has_many :orders
  has_one :open_order, :class_name => "Order", :conditions => "orders.status = 0"



  validates :name, presence: true
 # user.errors.full_messages
  #=> ["Name can't be blank"]
  validates :email, presence: true
  validates :email, presence: true
  validates :password, length: { minimum: 6 }
  validates :password_confirmation, presence: true


  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: true

  before_save :create_remember_token

  def has_product?(product)
    return false unless self.open_order
    items = self.open_order.order_items.collect(&:product_id) #this takes all the order items into the variable items
    items.include?(product.id)               #this checks whether the product_id of the product sent as
                                             #parameter matches with the product id of the objects present in items.
  end

  def placed_items
    self.orders.where("status = ?", Order::PROCESSED).collect{ |order| order.order_items.collect(&:product)}.flatten
  end

  def find_order_item(item)
    self.open_order.order_items.find_by_product_id(item)
  end


   # def feed
      #puts current_user
        # This is preliminary. See "Following users" for the full implementation.
        #Micropost.where("user_id = ?", id) if current_user
   # end





  def get_or_create_open_order
    self.open_order || self.orders.create(:status => Order::OPEN, :subtotal => 0)
  end

  private

  def create_remember_token
    if new_record?
      self.remember_token = SecureRandom.urlsafe_base64
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.limit(9).all.group_by(&:product_type)
  end

  def help
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper


end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    current_user = user
  end

   def signed_in?
    !current_user.nil?
  end

 def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in_user
    puts "hello"
    unless signed_in?

      redirect_to signin_path, notice: "Please sign in."
    end
 end

  private

    def user_from_remember_token
      remember_token = cookies[:remember_token]
      User.find_by_remember_token(remember_token) unless remember_token.nil?
    end

    def sign_out
      current_user=nil
      cookies.delete(:remember_token)
    end




end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "http://gravatar.com/avatar/gusstevens.png"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CityCakes</title>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="wrapper">
    <%= render 'shared/header' %>
   
      <%= render 'shared/navigation' %>
   <div id="container">  
     <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>

     <%= yield %>
   </div>
  </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  <span class="user">
    <%= link_to feed_item.user.name, feed_item.user %>
  </span>
  <span class="content"><%= feed_item.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
  </span>
</li>

app/views/shared/_footer.html.erb
<footer></footer>

app/views/shared/_header.html.erb
<div id="header">
  <%= link_to image_tag("city_cakes_logo.png"), root_path, id: "logo" %>
  <ul class="alr">
    <li><%= link_to "Home", root_path %></li>
    <li><%= link_to "Help", '/help' %></li>
    <% if signed_in? %>
    <li><%= link_to "Products", products_path %></li>
    <li><%= link_to "My Cart (#{current_user.open_order && current_user.open_order.order_items.count})", shopping_cart_items_path, :id => "in-cart-item-count" %></li>
    <li>
      <%= link_to 'Account', '#' %>
	    <ul >
        <li><%= link_to "Profile", user_path(current_user) %></li>
        <li><%= link_to "Settings",edit_user_path(current_user) %></li>
        <li class="divider"></li>
        <li>
          <%= link_to "Signout", signout_path, method: "delete" %>
        </li>
	    </ul>
    </li>
    <% if current_user.admin?  %>
    <li>
      <%= link_to 'Admin', '#' %>
	    <ul>
        <li><%= link_to "Company", '#' %></li>
        <li><%= link_to "Users", users_path %></li>
      </ul>
    </li>     
    <% end %>
    <% else %>
    <li><%= link_to "Sign in", signin_path %></li>
    <% end %>
  </ul>
  <%= form_tag "#", :id => "search" do %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("search") %>
  <% end %>
</div>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
  <%= f.text_area :content, placeholder: "Compose new micropost..." %>
</div>
<%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_navigation.html.erb
<div id="navigation" class="clearfix"> 
  <ul> 
        <li><%=link_to "Regular Cakes", products_path(:id => ProductType::REGULAR_CAKES) %></li> 
        <li><%=link_to "Wedding Cakes", products_path(:id => ProductType::WEDDING_CAKES) %></li> 
        <li><%=link_to "Special Cakes", products_path(:id => ProductType::SPECIAL_CAKES) %></li> 
        <li><%=link_to "Children Cakes",products_path(:id => ProductType::CHILDREN_CAKES) %></li> 
        <li><%=link_to "Numbered Cakes", products_path(:id => ProductType::NUMBERERD_CAKES) %></li> 
  </ul> 
</div> 

app/views/shared/_user_info.html.erb
<a href="<%= user_path(current_user) %>">
  <%= gravatar_for current_user %>
</a>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>