config/routes.rb
CityCakes::Application.routes.draw do

  resources :microposts, only: [ :create, :destroy ]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :home
  resources :products
  resources :shopping_cart_items

  match '/signup',  to: 'users#new'
  match '/help', to:    'home#help'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :orders do
    collection do
      post 'add_item', 'submit'
      get 'confirm', 'index'
      delete 'remove_item'
    end
  end

  root :to => 'home#index'

end

app/models/order.rb
class Order < ActiveRecord::Base

  has_many:order_items
  has_one:shipping_address

  OPEN = 0
  PLACED = 1
  PROCESSED = 2
  CANCELED = 3

  def recalculate
    total = 0
    self.order_items.each do |item|
      total += item.quantity * item.price
    end
    self.subtotal = total
    self.save!
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :get_open_order
  before_filter :signed_in_user

  def index

  @placed_items= current_user.placed_items

  end

  def add_item
    @product = Product.find(params[:id])
    if @product
      @open_order.order_items.create(:product_id => @product.id, :quantity => 1, :price => @product.price)
      @open_order.recalculate
    end
  end

  def remove_item
    @product = Product.find(params[:id])
    @open_order.order_items.find_by_product_id(@product).destroy
    @sub = @open_order.recalculate
  end

  def confirm
    @shipping_address = @open_order.build_shipping_address
  end


  def submit
    @shipping_address = @open_order.create_shipping_address(params[:shipping_address])
    @open_order.update_attribute(:status, Order::PROCESSED)
    flash[:notice] = "Your order has been placed!!"
    redirect_to orders_path
  end


  protected

  def get_open_order
    @open_order = current_user.get_or_create_open_order
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/add_item.js.erb
$("a.#product_<%= @product.id %>").replaceWith("<a class='cart-btn' href='javascript:;'>In Cart</a>");
$("#in-cart-item-count").text("My Cart (<%= current_user.open_order && current_user.open_order.order_items.count %>)");

app/views/orders/confirm.html.erb
<div class="product-form confirm-order clearfix">
<h1> CONFIRM ORDER </h1><br/> <br/>
<%= form_for @shipping_address, :url => submit_orders_path do |f| %>

<%= f.label :street %>
<%= f.text_field :street %><br/><br/> 

<%= f.label :city %>
<%= f.text_field :city %><br/><br/> 

<%= f.label :state %>
<%= f.text_field :state %><br/><br/>

<%= f.label :zip %>
<%= f.text_field:zip %><br/><br/>

<%= f.label :country %>
<%= f.text_field :country %><br/><br/>

<%= f.label :phone %>
<%= f.text_field :phone %><br/><br/>  

<%= f.submit "ship my order", class: "cart-btn" %>
<% end %>
</div>

app/views/orders/index.html.erb
<div id="order_history" class="clearfix">
<h3>This is your order history</h3>
<ul>
<% @placed_items.each do |a| %>


<li><%=  image_tag a.avatar.url(:thumb) %>
<h4><%= a.name %></h4>
<span>Rs.<%= a.price %></span>
</li>


<% end %>
</ul>

</div>

app/views/orders/remove_item.js.erb
$("a.#product_<%= @product.id %>").parents("tr").remove();