config/routes.rb
CityCakes::Application.routes.draw do

  resources :microposts, only: [ :create, :destroy ]

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :home
  resources :products
  resources :shopping_cart_items

  match '/signup',  to: 'users#new'
  match '/help', to:    'home#help'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  resources :orders do
    collection do
      post 'add_item', 'submit'
      get 'confirm', 'index'
      delete 'remove_item'
    end
  end

  root :to => 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to:company
  has_many :order_items
  has_attached_file :avatar, :styles => { :medium => "200x200>", :thumb => "100x100>", :large => "400x400" }

end

app/models/product_type.rb
class ProductType < ActiveRecord::Base

 REGULAR_CAKES = 1
 WEDDING_CAKES = 2
 SPECIAL_CAKES = 3
 CHILDREN_CAKES = 4
 NUMBERERD_CAKES = 5

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def create
    @product = Product.create( params[:product])
    redirect_to product_path(@product)
  end

  def index
    @products = if params[:id]
                  Product.where("product_type = ?", params[:id])
                else
                  Product.all
                end

  end
  def edit
    @product = Product.find(params[:id])
  end

  def update
 @product = Product.find(params[:id])


     if @product.update_attributes(params[:product])
       flash[:success] = "Product updated"
        redirect_to product_path(@product)


     else
        render 'edit'

     end
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

 def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product Deleted"
    redirect_to product_path

  end
end

app/helpers/products_helper.rb
module ProductsHelper


end

app/views/products/_product.html.erb
<li class="<%= c %>">
  <%= link_to image_tag(p.avatar.url(:medium),:size => "219x208"), product_path(p) %>
  <div class="clearfix">
    <h3><%= p.name %> </h3>
    <p class="all"> Rs.<span> <%= p.price %> </span> </p>
 
    <% if current_user && current_user.has_product?(p) %>
    <%= link_to 'In cart', "javascript:;", :class => "cart-btn", :id => "product_#{p.id}" %>
    <% else %>
    <%= link_to 'add to cart', add_item_orders_path(:id => p), "data-remote" => true, "data-method" => "post",:class => "cart-btn", :id => "product_#{p.id}" %>
    <% end %>
  
  </div>
</li>

app/views/products/edit.html.erb
<%= provide(:title, 'Add new product') %>
<div class="product-form">

<h1>Update Product</h1>

         <%= form_for @product, :html => {:multipart => true } do |f| %>
 
            <%= f.label :name %>
            <%= f.text_field :name %><br/><br/>
    
            <%= f.label :product_type %>
            <%= f.select :product_type, ProductType.all.map{|p| [p.name,p.id]} %><br/><br/>

            <%= f.label  :description %>
            <%= f.text_area :description %><br/><br/>
            
            <%=  f.label  :avatar, "Photo" %>
            <%= f.file_field :avatar %><br/><br/>
            
            <%= f.label  :price %>
            <%= f.number_field :price %><br/><br/>

            <%= f.label :weight %>
            <%= f.text_field :weight %><br/><br/><br/>
            

            <%= f.submit "Update", class: "cart-btn" %>
     
     <% end %>
</div>

app/views/products/index.html.erb
<% if current_user && current_user.admin?  %>
<%= link_to "add new product", new_product_path %>
<% end %>

<div class="cake-view">
  <div class="featured-cakes clearfix">
    <div class="featured-cakes-header clearfix">
      <% if params[:id] %>
      <h2 class="all"><%= ProductType.find(params[:id]).name %></h2>
      <% end %>
    </div>
    <ul>
      <% @products.each_with_index do |product, index| %>
      <% clazz = ((index+1)%3 == 0) ? "no-right-space" : "" %>
      <%= render :partial => "product", :locals => {:p => product, :c => clazz } %>

      <% end %>
    </ul>
  </div> 
</div> 

app/views/products/new.html.erb
<%= provide(:title, 'Add new product') %>

<div class="product-form clearfix">
  <h1> Add Products</h1>
         <%= form_for @product, :html => {:multipart => true } do |f| %>
 
            <%= f.label :name %>
            <%= f.text_field :name %><br /><br />
    
            <%= f.label :product_type %>
            <%= f.select :product_type, ProductType.all.map{|p| [p.name,p.id]} %><br /><br />

            <%= f.label  :description %>
            <%= f.text_area :description %><br /><br />
            
            <%=  f.label  :avatar %>
            <%= f.file_field :avatar %><br /><br />
            
            <%= f.label  :price %>
            <%= f.number_field :price %><br /><br />

            <%= f.label :weight %>
            <%= f.text_field :weight %><br /><br />
            

            <%= f.submit "Add Product", class: "btn btn-large btn-primary" %>
     
     <% end %>

</div>

app/views/products/show.html.erb
<div class="cake-details-view">
 <div class="cake-details clearfix">
    <%= image_tag @product.avatar.url(:large) %>
    <h3><%= @product.name %></h3>
    <p><%= @product.description %></p>
    <span> Price: Rs.<%= @product.price %></span>
    <% if current_user && current_user.has_product?(@product) %>
    <br/><br/>
    <%= link_to 'In cart', "javascript:;", :class => "cart-btn", :id => "product_#{@product.id}" %>
    <% else %>
    <br/><br/>
    <%= link_to 'add to cart', add_item_orders_path(:id => @product), "data-remote" => true, "data-method" => "post",:class => "cart-btn", :id => "product_#{@product.id}" %><br/><br/>
    <% end %>
   <% if current_user.admin? %>

  <%= link_to 'edit product', edit_product_path,:class => "cart-btn" %>
  
  <%= link_to "delete", p, method: :delete, confirm: "You sure?",:class => "cart-btn" %>
   <% end %>
 </div>

</div>